package ro.uaic.info.doctoravailabilitymanagementmicroservice.repositories;

import ro.uaic.info.doctoravailabilitymanagementmicroservice.entities.DoctorInvestigationExpense;

public interface DoctorInvestigationExpenseCustomRepository extends FilterAndSortUtils<DoctorInvestigationExpense> {
}
